export enum ETagTypes {
  GET_RANDOM_MOVIE = "GET_RANDOM_MOVIE",
  GET_AUTH_USER = "GET_AUTH_USER",
  GET_MOVIE_WITH_PARAMS = "GET_MOVIE_WITH_PARAMS",
  ADD_FAVORITES = "ADD_FAVORITES",
  REMOVE_FAVORITES = "REMOVE_FAVORITES",
}
